[package]
edition = "2021"
name = "anno"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
axum = "0.7.5"
axum-aws-lambda = "0.7.0"
dotenv = "0.15.0"
futures = "0.3.30"
git2 = "0.18.3"
hex = "0.4.3"
hmac-sha256 = "1.1.7"
hyper = "1.3.1"
lambda_http = "0.11.1"
openssl = {version = "0.10.64", features = ["vendored"]}
regex-lite = "0.1.6"
reqwest = {version = "0.12.4", features = ["json"]}
serde = "1.0.202"
serde_json = "1.0.117"
serde_path_to_error = "0.1.16"
subtle = "2.5.0"
tokio = {version = "1.38.0", features = ["rt-multi-thread", "macros"]}
tower = "0.4.13"
tower-http = {version = "0.5.2", features = ["cors", "compression-gzip", "compression-deflate", "trace"]}
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[package.metadata.lambda.deploy]
timeout = 300
tags = { "Name"="anno","Env"="prod" }
