[workspace]
default-members = [
  "api",
  "action",
  "shared",
]
members = [
  "api",
  "shared",
  "action",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.81"
api = {path = "api"}
axum = "0.7.5"
chrono = "0.4.38"
dotenv = "0.15.0"
hyper = "1.3.1"
serde = "1.0.202"
serde_json = "1.0.117"
serde_path_to_error = "0.1.16"
shared = {path = "shared"}
time = {version = "0.3.36", features = ["local-offset"]}
tokio = {version = "1.38.0", features = ["rt-multi-thread", "macros"]}
tracing = "0.1.40"
tracing-subscriber = {version = "0.3.18", features = ["time"]}
