[package]
edition = "2021"
name = "github_action"
version = "0.1.0"

[dependencies]
anyhow.workspace = true
common.workspace = true
dotenv.workspace = true
tokio.workspace = true
tracing.workspace = true
