name: Release

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/**'

jobs:
  cargo_check:
    name: Cargo Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-build-cache

      - name: Release lambda
        run: |
          pip install cargo-lambda
          cargo lambda build --release
          cargo lambda deploy --enable-function-url \
            --env-var ADR_REPO_FULL_NAME=The-Sole-Supplier/ADRs \
            --env-var ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }} \
            --env-var ANTHROPIC_BASE_URL=https://api.anthropic.com \
            --env-var CHAT_GPT_MODEL=gpt-4o-2024-08-06 \
            --env-var CLAUDE_MODEL=claude-3-5-sonnet-20241022 \
            --env-var GITHUB_APP_ID=952862 \
            --env-var GITHUB_APP_INSTALLATION_ID=53127890 \
            --env-var GITHUB_APP_PRIVATE_KEY_BASE64=${{ secrets.GH_APP_PRIVATE_KEY_BASE64 }} \
            --env-var GITHUB_BASE_URL=https://api.github.com \
            --env-var GITHUB_BOT_USER_ID=176515466 \
            --env-var GITHUB_WEBHOOK_SECRET=${{ secrets.GH_WEBHOOK_SECRET }} \
            --env-var JIRA_API_KEY=${{ secrets.JIRA_API_KEY }} \
            --env-var JIRA_BASE_URL=https://thesolesupplier.atlassian.net \
            --env-var JIRA_BOT_USER_ID=5e5ab50ba17f930c9b964563 \
            --env-var JIRA_COMMENT_ENABLED=true \
            --env-var JIRA_WEBHOOK_SECRET=${{ secrets.JIRA_WEBHOOK_SECRET }} \
            --env-var LOG_LEVEL=INFO \
            --env-var OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --env-var OPENAI_BASE_URL=https://api.openai.com/v1 \
            --env-var PR_COMMENT_ENABLED=true \
            --env-var REPOS_DIR=/tmp/repos \
            --env-var SLACK_MESSAGE_ENABLED=true \
            --env-var SLACK_WEBHOOK_URL=https://hooks.slack.com/services/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 \
            --env-var WEBHOOK_VALIDATION=true
        env:
          AWS_DEFAULT_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
