name: Release

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  cargo_check:
    name: Cargo Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-build-cache

      - name: Release lambda
        run: |
          pip install cargo-lambda
          cargo lambda build --release
          cargo lambda deploy --enable-function-url
        env:
          AWS_DEFAULT_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ADR_REPO_FULL_NAME: The-Sole-Supplier/ADRs
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ANTHROPIC_BASE_URL: https://api.anthropic.com
          ANTHROPIC_MODEL: claude-3-opus-20240229
          GITHUB_APP_ID: 952862
          GITHUB_APP_INSTALLATION_ID: 53127890
          GITHUB_APP_PRIVATE_KEY_BASE64: ${{ secrets.GH_APP_PRIVATE_KEY_BASE64 }}
          GITHUB_BASE_URL: https://api.github.com
          GITHUB_SECRET: ${{ secrets.GH_SECRET }}
          JIRA_API_KEY: ${{ secrets.JIRA_API_KEY }}
          JIRA_BASE_URL: https://thesolesupplier.atlassian.net
          LLM_PROVIDER: anthropic
          LOG_LEVEL: INFO
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: https://api.openai.com/v1
          OPENAI_MODEL: gpt-4o-2024-05-13
          REPOS_DIR: '/tmp/repos'
          SLACK_MESSAGE_ENABLED: true
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
          WEBHOOK_VALIDATION: true
